name: example workflow
on:
  push

permissions:
  id-token: write

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          role-session-name: oidc
          aws-region: ap-northeast-1
      - run: aws s3 ls ss49919201
